/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.widgets;

import com.health.installer.fund.utils.Util;
import com.health.objects.GetAvailibleRooms;
import com.health.objects.GetAvailibleServices;
import com.health.objects.GetProcedure;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Inspiron
 */
public class ServiceRequest extends javax.swing.JPanel implements Procedure.OnOrderChanged, ServiceRoomWgt.onSelectionChanged {

    /**
     * Creates new form ServiceRequest
     */
    private GetProcedure.ServicesGroup mGroup;
    private GetProcedure.Procedure mProcedure;
    private Procedure mParent;

    private int current_pos = -1;
    private List<Integer> indexes;

    public void setData(GetProcedure.Procedure procedure, GetProcedure.ServicesGroup group, Procedure parent) {
        mProcedure = procedure;
        mGroup = group;
        mParent = parent;
        mParent.registerListener(this);

        CountSpinner.setValue(group.count);
        note.setText(group.note_med);

        System.out.println("----data ");
        System.out.println(group.rooms);
        System.out.println(group.services);

        for (int i = 0; i < group.services.size(); i++) {
            List<Object> objs = new ArrayList<>();
            Util.getAllObjects((DefaultMutableTreeNode) rooms_matcher.Services.getModel().getRoot(), objs);
            for (Object d : objs) {
                if (d instanceof GetAvailibleServices.Service) {
                    if (((GetAvailibleServices.Service) d).service_id == group.services.get(i).service_id) {
                        rooms_matcher.Services.toggleNode(Util.findNode((DefaultMutableTreeNode) rooms_matcher.Services.getModel().getRoot(), d));
                    }
                }
            }
        }
        for (int i = 0; i < group.rooms.size(); i++) {
            List<Object> objs = new ArrayList<>();
            Util.getAllObjects((DefaultMutableTreeNode) rooms_matcher.Rooms.getModel().getRoot(), objs);
            for (Object d : objs) {
                if (d instanceof GetAvailibleRooms.Room) {
                    if (((GetAvailibleRooms.Room) d).room_id == group.rooms.get(i).room_id) {
                        rooms_matcher.Rooms.toggleNode(Util.findNode((DefaultMutableTreeNode) rooms_matcher.Rooms.getModel().getRoot(), d));
                    }
                }
            }
        }

    }

    public ServiceRequest() {
        initComponents();
        rooms_matcher.registerListener(this);
        note.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                update();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                update();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                update();
            }

            void update() {
                mGroup.note_med = note.getText();
            }
        });

        CountSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {

                mGroup.count = (int) CountSpinner.getValue();
            }
        });
    }

    @Override
    public void newData(List<GetAvailibleServices.Service> services, List<GetAvailibleRooms.Room> rooms) {
        mGroup.rooms.clear();
        mGroup.rooms.addAll(rooms);
        mGroup.services.clear();
        mGroup.services.addAll(services);

    }

    @Override
    public void update() {
        int pos = -1;
        for (int i = 0; i < mParent.Orders.size(); i++) {
            if (mParent.Orders.get(i).contains(mGroup)) {
                pos = i;
                break;
            }
        }
        this.current_pos = pos;
        indexes = mParent.getAvailibleOrders(false, mGroup);
        String[] labels = new String[indexes.size()];
        for (int i = 0; i < indexes.size(); i++) {
            labels[i] = Procedure.Order_Labels[indexes.get(i)];
        }

        DefaultComboBoxModel<String> t = new DefaultComboBoxModel<String>(labels);
        order_list.setModel(t);
        order_list.setSelectedIndex(indexes.indexOf(pos));
        mGroup.order = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rooms_matcher = new com.health.widgets.ServiceRoomWgt();
        jLabel1 = new javax.swing.JLabel();
        remove_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        order_list = new javax.swing.JComboBox<>();
        CountSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Service Request");

        remove_btn.setText("Remove");
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        note.setColumns(20);
        note.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        note.setRows(5);
        jScrollPane2.setViewportView(note);

        jLabel2.setText("Note");

        jLabel3.setText("Order");

        order_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        order_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_listActionPerformed(evt);
            }
        });

        jLabel4.setText("count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rooms_matcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(order_list, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(CountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(remove_btn))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(order_list, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rooms_matcher, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void order_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_listActionPerformed
        // TODO add your handling code here:
        int pos = order_list.getSelectedIndex();
        if (pos != indexes.indexOf(current_pos)) {
            mParent.transferOrder(current_pos, indexes.get(pos), mGroup);
        }
    }//GEN-LAST:event_order_listActionPerformed

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        // TODO add your handling code here:
        mProcedure.services.remove(mGroup);
        mParent.unregisterListener(this);
        mParent.removeOrder(mGroup);
        Container c = getParent();
        c.remove(this);
        c.revalidate();
        c.repaint();
    }//GEN-LAST:event_remove_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CountSpinner;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea note;
    private javax.swing.JComboBox<String> order_list;
    private javax.swing.JButton remove_btn;
    private com.health.widgets.ServiceRoomWgt rooms_matcher;
    // End of variables declaration//GEN-END:variables

}
