/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.widgets;

import com.health.objects.GetCondtion;
import com.health.objects.StopCondtion;
import com.health.objects.Types;
import com.health.project.medteam.Globals;
import javax.swing.SwingUtilities;

/**
 *
 * @author Inspiron
 */
public class CondtionDocker extends javax.swing.JPanel {

    /**
     * Creates new form CondtionDocker
     */
    private GetCondtion.Condtion cond;

    public CondtionDocker() {
        initComponents();
    }

    public void setData(GetCondtion.Condtion c) {
        CondtionView.setData(c);
        cond = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CondtionView = new com.health.widgets.CondtionViewer();
        Stop = new javax.swing.JButton();

        jScrollPane1.setViewportView(CondtionView);

        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        // TODO add your handling code here:
        Stop.setText("Please wait");

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                StopCondtion.StopCondtion(Globals.patien_id, cond.condtion_id);
                cond.state = Types.State_Cond_History;
                Globals.update();
                Globals.showMsg("Condtion Stopped Successfully");
                Stop.setText("Stop");

            }
        });

    }//GEN-LAST:event_StopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.health.widgets.CondtionViewer CondtionView;
    private javax.swing.JButton Stop;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
