/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.widgets;

import com.health.objects.GetAvailibleRooms;
import com.health.objects.GetAvailibleServices;
import com.health.objects.GetCondtion;
import com.health.objects.GetProcedure;
import com.health.objects.StartCondtion;
import com.health.objects.Types;
import com.health.project.medteam.Globals;
import com.health.project.medteam.Util;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author Inspiron
 */
public class CondtionContainer extends javax.swing.JPanel {

    /**
     * Creates new form CondtionContainer
     */
    private GetCondtion.Condtion condtion;
    
    public CondtionContainer() {
        initComponents();
        
    }
    
    public void setData(GetCondtion.Condtion condtion) {
        
        this.condtion = condtion;
        Condtion.setData(this.condtion, false);
        
    }
    
    public GetCondtion.Condtion get() {
        
        return this.condtion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Condtion = new com.health.widgets.Condtion();
        jPanel1 = new javax.swing.JPanel();
        StartBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1056, 760));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(Condtion);

        add(jScrollPane1);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(1056, 100));

        StartBtn.setText("Start Condtion");
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(StartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        
        if (condtion.name.length() == 0
                || condtion.desc.length() == 0 || condtion.activation_period <= 0) {
            Globals.showMsg("Please Enter All Fields Correctly");
            return;
        }
        
        for (int x = 0; x < condtion.procedures.size(); x++) {
            
            GetProcedure.Procedure procedure = condtion.procedures.get(x);
            
            boolean check = Util.checkProcedure(procedure);
            if (!check) {
                return;
            }
            
        }
        for (int x = 0; x < condtion.attached_procedures.size(); x++) {
            GetProcedure.Procedure procedure = condtion.attached_procedures.get(x);
            
            boolean check = Util.checkProcedure(procedure);
            if (!check) {
                return;
            }
        }
        
        StartBtn.setText("Please wait...");
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                long id = StartCondtion.StartCondtion(Globals.patien_id, condtion);
                GetCondtion.Condtion c = GetCondtion.getCondtion(Globals.patien_id, id);
                Globals.activeCondtions.add(c);
                Globals.Updater d;
                if ((d = Globals.ActiveCondtions.get()) != null) {
                    d.update();
                }
                Globals.startCondtion.get().dispose();
                Globals.showMsg("Condition Started Successfully");
                StartBtn.setText("Start");
            }
        });
        

    }//GEN-LAST:event_StartBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.health.widgets.Condtion Condtion;
    private javax.swing.JButton StartBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
