/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.widgets;

import com.health.objects.GetPersonalData;
import com.health.project.medteam.Globals;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Inspiron
 */
public class OpenHealthRecord extends javax.swing.JPanel {

    /**
     * Creates new form OpenHealthRecord
     */
    public OpenHealthRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        OpenID = new javax.swing.JButton();

        jLabel1.setText("Enter ID");

        OpenID.setText("Open Patient Profile");
        OpenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpenID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(OpenID)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OpenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenIDActionPerformed
        // TODO add your handling code here:

        String Ids = Id.getText();
        final long id;
        long id1 = 0;
        try {
            id1 = Long.parseLong(Ids);
        } catch (Exception e) {
            System.out.println("1");
            Globals.showMsg("Please Enter a Valid id number");
            id1 = 0;
            return;
        }

        if (id1 == 0) {
            System.out.println("2");

            Globals.showMsg("Please Enter a Valid id number");
            return;
        }

        id = id1;
        OpenID.setText("Please wait...");
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    GetPersonalData.GetPersonalData(id).name = "";

                } catch (Exception e) {
                    e.printStackTrace();
                    OpenID.setText("Open Patient Profile");
                    Globals.showMsg("Please Enter a Valid id number");
                    return;
                }
                Globals.setPatient(id, 0);
                JFrame frame = new JFrame("Patient");
                frame.getContentPane().add(new HealthRecordDocker(), BorderLayout.CENTER);
                Dimension d = new Dimension(1200, 800);
                frame.setSize(d);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
                frame.pack();
                Globals.PatientProfile.get().dispose();
            }
        });


    }//GEN-LAST:event_OpenIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton OpenID;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
